apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer-deployment
spec:
  selector:
    matchLabels:
      app: customer-deployment
  template:
    metadata:
      labels:
        app: customer-deployment
    spec:
      containers:
        - name: customer-service
          image: customer-service:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: '1024Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: default
  labels:
    app: customer-service
spec:
  selector:
    app: customer-deployment
  ports:
    - name: customer-service-port
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: ''
