apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: customer-service.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: customer-service
                port:
                  number: 80
    - host: order-service.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 80
    - host: keycloak.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
    - host: krakend.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: krakend-service
                port:
                  number: 80
